### ISSUE TITLE
有路人着手进行翻译了，一起？

### ISSUE THREAD

**Issue by sumbrez** [SinnohZeng/OxygenNotIncluded-ChineseTranslation#1]
klei论坛里也回复你的帖子了，但估计这里比较快。
（静淮街表示离得挺近）

**Comment by sumbrez** [comment]
之前一直用写代码的编辑器写（因为fork出来的.po没有指定语言字符集，也是因为klei给的pot很“简洁”），刚才翻译的一部分用poedit写的，发现例如`{Symptoms}\n\nInfected by`这种，poedit在`\n`后插入实际的换行，和原来的行号对不上了，所以决定不用了。

**Comment by sinnohzeng** [comment]
@sumbrez Klei 论坛里有一个 ID 为 deloquac 哥们儿似乎已经完全翻译完了文本，只差官方更新内嵌字体功能。我这边还没翻译几句呢……要不直接请他分享一下他的翻译？我就不重新搞了……
我用 poedit 的时候感觉有些地方换行很怪，不知道会不会影响到最后的翻译结果。

**Comment by sumbrez** [comment]
如果他是个人最近开始的，我怀疑是不是机翻，因为之前在贴吧里看到了有人提供翻译文件和字体，是机翻的，我现在参与的repo的一个issue提到这个事了。
Klei论坛那个帖子第三页还有个叫Kurax的，说
>I'm Kenneth from Project Gutenberg whom has sent you an email before, we're interested in translating the game into Chinese.

这个倒是值得关注，但我觉得Klei不会合作，因为肯定有“志愿者”。
（原来deloquac之前在第三页就有帖子了，但可能没写中文所以没在意吧）
***
poeidt的换行一开始我以为只是在poedit里显示的时候加换行，但是是实实在在地在文件里加换行了，这样首先必然搞乱行号了，不好协作。

**Comment by xiaohuang20161012** [comment]
poedit换行没关系，很好解决，你们有QQ吗？一起翻译啊

**Comment by sumbrez** [comment]
https://github.com/FuchsLee/Oxygen_Not_Included-zh

**Comment by sinnohzeng** [comment]
我认为如果所有人都用 Poedit 翻译的话进度就好统一。
我想跟着[FuchLee](https://github.com/FuchsLee/Oxygen_Not_Included-zh)的进度走，慢慢翻译，不用贴吧里的机翻。
